USE [master]
GO

/****** Object:  Database [mytestdb]    Script Date: 3/29/2022 11:00:52 PM ******/
DROP DATABASE [mytestdb]
GO

/****** Object:  Database [mytestdb]    Script Date: 3/29/2022 11:00:52 PM ******/
CREATE DATABASE [mytestdb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'mytestdb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\mytestdb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'mytestdb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\mytestdb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [mytestdb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [mytestdb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [mytestdb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [mytestdb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [mytestdb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [mytestdb] SET ARITHABORT OFF 
GO

ALTER DATABASE [mytestdb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [mytestdb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [mytestdb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [mytestdb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [mytestdb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [mytestdb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [mytestdb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [mytestdb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [mytestdb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [mytestdb] SET  DISABLE_BROKER 
GO

ALTER DATABASE [mytestdb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [mytestdb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [mytestdb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [mytestdb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [mytestdb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [mytestdb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [mytestdb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [mytestdb] SET RECOVERY FULL 
GO

ALTER DATABASE [mytestdb] SET  MULTI_USER 
GO

ALTER DATABASE [mytestdb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [mytestdb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [mytestdb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [mytestdb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [mytestdb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [mytestdb] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [mytestdb] SET QUERY_STORE = OFF
GO

ALTER DATABASE [mytestdb] SET  READ_WRITE 
GO

